{{- if and .Values.dashboard.enabled .Values.dashboard.auth.enabled (not .Values.dashboard.auth.existingSecret) }}
kind: Secret
apiVersion: v1
metadata:
  name: juicefs-dashboard-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: dashboard-secret
    {{- include "juicefs-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.dashboard.auth.username }}
  password: {{ .Values.dashboard.auth.password }}
{{- end }}
