{{- $certEnabled := .Values.webhook.certManager.enabled }}

{{- if eq .Values.mountMode "sidecar" }}
{{- if not $certEnabled }}
kind: Secret
apiVersion: v1
metadata:
  name: juicefs-webhook-certs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: webhook-secret
    {{- include "juicefs-csi.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ b64enc (include "webhook.caBundleCertPEM" .) }}
  tls.crt: {{ b64enc (include "webhook.certPEM" .) }}
  tls.key: {{ b64enc (include "webhook.keyPEM" .) }}
{{- end }}
{{- end }}
