apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicefs-s3-gateway
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "juicefs-s3-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "juicefs-s3-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "juicefs-s3-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: format
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          command:
            - sh
            - -c
            {{- if .Values.secret.token }}
            - juicefs auth ${name} --token=${token} {{ if .Values.secret.bucket }}--bucket=${bucket}{{ end }} --access-key=${accesskey} --secret-key=${secretkey}
            {{- else }}
            - juicefs format ${metaurl} ${name} --storage=${storage} --bucket=${bucket} --access-key=${accesskey} --secret-key=${secretkey} {{ .Values.formatOptions }}
            {{- end }}
          envFrom:
            - secretRef:
                name: juicefs-secret
          env:
            - name: accesskey
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: access-key
            - name: secretkey
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: secret-key
            {{- if .Values.initEnvs }}
{{ toYaml .Values.initEnvs | indent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.secret.token }}
            - mountPath: /root/.juicefs
              name: jfs-root-dir
            {{- end }}
      containers:
        - name: gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          command:
            - sh
            - -c
            {{- if .Values.secret.token }}
            - juicefs gateway ${VOL_NAME} ${NODE_IP}:{{ .Values.port }} {{ .Values.options }}
            {{- else }}
            - juicefs gateway ${METAURL} ${NODE_IP}:{{ .Values.port }} --metrics=${NODE_IP}:{{ .Values.metricsPort }} {{ .Values.options }}
            {{- end }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.secret.token }}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: token
            - name: VOL_NAME
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: name
            {{- else }}
            - name: METAURL
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: metaurl
            {{- end }}
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: secret-key
            {{- if .Values.envs }}
{{ toYaml .Values.envs | indent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
            - containerPort: {{ .Values.metricsPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.secret.token }}
            - mountPath: /root/.juicefs
              name: jfs-root-dir
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      volumes:
        {{- if .Values.secret.token }}
        - emptyDir: {}
          name: jfs-root-dir
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
