{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "juicefs-s3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.token }}

  {{- with .Values.secret }}
  name: {{ .name | b64enc | quote }}
  token: {{ .token | b64enc | quote }}
  {{- if .accessKey }}
  access-key: {{ .accessKey | b64enc | quote }}
  {{- end }}
  {{- if .secretKey }}
  secret-key: {{ .secretKey | b64enc | quote }}
  {{- end }}
  {{- if .bucket }}
  bucket: {{ .bucket | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- else }}

  {{- with .Values.secret }}
  name: {{ .name | b64enc | quote }}
  metaurl: {{ .metaurl | b64enc | quote }}
  {{- if .storage }}
  storage: {{ .storage | b64enc | quote }}
  {{- end }}
  {{- if .accessKey }}
  access-key: {{ .accessKey | b64enc | quote }}
  {{- end }}
  {{- if .secretKey }}
  secret-key: {{ .secretKey | b64enc | quote }}
  {{- end }}
  {{- if .bucket }}
  bucket: {{ .bucket | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- end }}

  {{- with .Values.secret }}
  {{- if .encrypt_rsa_key }}
  encrypt_rsa_key: {{ .encrypt_rsa_key | b64enc | quote }}
  {{- end }}
  {{- if .JFS_RSA_PASSPHRASE }}
  JFS_RSA_PASSPHRASE: {{ .JFS_RSA_PASSPHRASE | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
